//! Phase 0/1 smoke test: confirm the v2 program loads under LiteSVM and the
//! placeholder `ping` handler (discriminator 254) returns Ok(()) when invoked
//! with a single signer account. This proves three things end-to-end:
//!   1. `cargo build-sbf` produces a working .so.
//!   2. Anchor v2's generated entrypoint dispatches on `#[discrim = N]`
//!      single-byte discriminators with no args.
//!   3. The Anchor v2 `Signer` constraint validates a signed payer.
//!
//! Unlike the legacy suite (gated behind `--features legacy-tests`), this
//! test does NOT depend on `tests/common/`.

use litesvm::LiteSVM;
use solana_sdk::{
    instruction::{AccountMeta, Instruction},
    pubkey::Pubkey,
    signature::{Keypair, Signer},
    transaction::Transaction,
};
use std::path::PathBuf;

/// Path to the compiled BPF artifact emitted by `cargo build-sbf`.
fn program_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target/deploy/percolator_prog.so");
    assert!(
        p.exists(),
        "BPF binary not found at {:?} — run `cargo build-sbf` first",
        p,
    );
    p
}

/// Anchor v2 `#[discrim = 254]` on `ping` — see src/lib.rs.
const PING_DISCRIM: u8 = 254;

/// Must match `declare_id!` in src/lib.rs. Anchor v2's generated entrypoint
/// validates the runtime-supplied program id against `crate::ID` and rejects
/// with `IncorrectProgramId` on mismatch, so the test can't deploy under a
/// random pubkey the way the legacy native program did.
const PROGRAM_ID: Pubkey =
    solana_sdk::pubkey!("Perco1ator111111111111111111111111111111111");

#[test]
fn ping_handler_returns_ok() {
    let mut svm = LiteSVM::new();
    let program_id = PROGRAM_ID;
    let bytes = std::fs::read(program_path()).expect("read program .so");
    svm.add_program(program_id, &bytes).expect("load program");

    let payer = Keypair::new();
    svm.airdrop(&payer.pubkey(), 1_000_000_000)
        .expect("airdrop payer");

    // Wire format: [discriminator]. `ping` takes no args, so no Borsh tail.
    let ix = Instruction {
        program_id,
        accounts: vec![AccountMeta::new_readonly(payer.pubkey(), true)],
        data: vec![PING_DISCRIM],
    };

    let tx = Transaction::new_signed_with_payer(
        &[ix],
        Some(&payer.pubkey()),
        &[&payer],
        svm.latest_blockhash(),
    );

    let result = svm.send_transaction(tx);
    assert!(
        result.is_ok(),
        "ping tx should succeed; got: {:#?}",
        result.err(),
    );
}

#[test]
fn ping_unknown_discriminator_fails() {
    // Sanity: any discriminator other than 254 (the only handler currently
    // installed) must hit the InstructionFallbackNotFound path generated by
    // the #[program] dispatch.
    let mut svm = LiteSVM::new();
    let program_id = PROGRAM_ID;
    let bytes = std::fs::read(program_path()).expect("read program .so");
    svm.add_program(program_id, &bytes).expect("load program");

    let payer = Keypair::new();
    svm.airdrop(&payer.pubkey(), 1_000_000_000)
        .expect("airdrop payer");

    let ix = Instruction {
        program_id,
        accounts: vec![AccountMeta::new_readonly(payer.pubkey(), true)],
        data: vec![0u8], // tag 0 (InitMarket) is not yet wired up
    };
    let tx = Transaction::new_signed_with_payer(
        &[ix],
        Some(&payer.pubkey()),
        &[&payer],
        svm.latest_blockhash(),
    );

    let result = svm.send_transaction(tx);
    assert!(
        result.is_err(),
        "tx with unmapped discriminator must fail",
    );
}
